"""Initial migration

Revision ID: c60247ec5093
Revises: 
Create Date: 2025-08-22 22:24:15.135460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60247ec5093'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_uid', sa.String(length=128), nullable=True),
    sa.Column('cat_label', sa.String(length=128), nullable=False),
    sa.Column('cat_description', sa.Text(), nullable=True),
    sa.Column('cat_is_featured', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cat_is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cat_banner', sa.String(length=256), nullable=True),
    sa.Column('cat_icon', sa.String(length=256), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_icon'),
    sa.UniqueConstraint('cat_uid')
    )
    op.create_table('ps_device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_tokens_id', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=True),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token'),
    sa.UniqueConstraint('device_tokens_id')
    )
    op.create_table('ps_stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_uid', sa.String(length=128), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('store_address', sa.String(length=255), nullable=True),
    sa.Column('store_city', sa.String(length=128), nullable=True),
    sa.Column('store_country', sa.String(length=128), nullable=True),
    sa.Column('store_phone', sa.String(length=128), nullable=True),
    sa.Column('store_email', sa.String(length=128), nullable=True),
    sa.Column('store_website', sa.String(length=255), nullable=True),
    sa.Column('store_logo', sa.String(length=255), nullable=True),
    sa.Column('store_is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_uid')
    )
    op.create_table('ps_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_uid', sa.String(length=128), nullable=True),
    sa.Column('u_name', sa.String(length=128), nullable=True),
    sa.Column('u_firstname', sa.String(length=128), nullable=True),
    sa.Column('u_lastname', sa.String(length=128), nullable=True),
    sa.Column('u_username', sa.String(length=128), nullable=True),
    sa.Column('u_mobile', sa.String(length=128), nullable=True),
    sa.Column('u_address', sa.String(length=128), nullable=True),
    sa.Column('u_country', sa.String(length=128), nullable=True),
    sa.Column('u_state', sa.String(length=128), nullable=True),
    sa.Column('u_city', sa.String(length=128), nullable=True),
    sa.Column('u_email', sa.String(length=128), nullable=True),
    sa.Column('u_image_link', sa.Text(), nullable=True),
    sa.Column('u_status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('u_password', sa.String(length=128), nullable=True),
    sa.Column('u_first_login', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('u_id_scan', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_token', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_uid'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('ps_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=False),
    sa.Column('header', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['u_uid'], ['ps_users.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_table('ps_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_uid', sa.String(length=128), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_brand', sa.String(length=128), nullable=True),
    sa.Column('product_barcode', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('product_is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ps_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_uid')
    )
    op.create_table('ps_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_uid', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('store_address', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('receipt_image', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['u_uid'], ['ps_users.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_uid')
    )
    op.create_table('ps_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_uid', sa.String(length=128), nullable=True),
    sa.Column('store_name', sa.String(length=128), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('scan_image', sa.String(length=256), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ps_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_uid')
    )
    op.create_table('ps_comparison_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comparison_uid', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('compared_stores', sa.Text(), nullable=True),
    sa.Column('best_price', sa.Float(), nullable=False),
    sa.Column('best_store_id', sa.Integer(), nullable=False),
    sa.Column('comparison_date', sa.DateTime(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['best_store_id'], ['ps_stores.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ps_products.id'], ),
    sa.ForeignKeyConstraint(['u_uid'], ['ps_users.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_uid')
    )
    op.create_table('ps_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fav_uid', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ps_products.id'], ),
    sa.ForeignKeyConstraint(['u_uid'], ['ps_users.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fav_uid')
    )
    op.create_table('ps_price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_uid', sa.String(length=128), nullable=True),
    sa.Column('u_uid', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ps_products.id'], ),
    sa.ForeignKeyConstraint(['u_uid'], ['ps_users.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_uid')
    )
    op.create_table('ps_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price_uid', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('price_date', sa.DateTime(), nullable=False),
    sa.Column('price_is_promo', sa.Boolean(), nullable=True),
    sa.Column('price_promo_end', sa.DateTime(), nullable=True),
    sa.Column('price_source', sa.String(length=50), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ps_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['ps_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_uid')
    )
    op.create_table('ps_receipt_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_uid', sa.String(length=128), nullable=True),
    sa.Column('receipt_uid', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category_uid', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_uid'], ['ps_categories.cat_uid'], ),
    sa.ForeignKeyConstraint(['receipt_uid'], ['ps_receipts.receipt_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ps_receipt_items')
    op.drop_table('ps_prices')
    op.drop_table('ps_price_alerts')
    op.drop_table('ps_favorite')
    op.drop_table('ps_comparison_history')
    op.drop_table('ps_scans')
    op.drop_table('ps_receipts')
    op.drop_table('ps_products')
    op.drop_table('ps_notification')
    op.drop_table('ps_users')
    op.drop_table('ps_stores')
    op.drop_table('ps_device_tokens')
    op.drop_table('ps_categories')
    # ### end Alembic commands ###
